### ISSUE TITLE
Registreringsløsningen, Datasett detaljside:   Refresh av siden fjerner oppsettet

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2266]
Dersom en har valgt flere spåk og jobber med registrering i feltene og så trykker Refresh (F5) fjernes valg av språk øverst  (Settes til NB)   og seksjonen en jobber i blir kollapset.   (Data forsvinner ikke)

**Comment by azaxarov** [comment]
@joebrreg @lillelars @sindresandvik2 @stigbd 

Dataset registration application determines active languages by parsing response from the back end in order to get a unique list of used languages. An important factor is that languages are not saved explicitly in the back end. Toggling languages on and off does not result in new fields being saved, meaning that no additional language information is saved. The result is the behaviour stated in this issue.

It is possible to implement workarounds, such as saving language choice in local or session storage. There are two clear disadvantages to such approach. First, saved language choice is bound to user's current machine. This means that if a user was to log in on a different machine, the language choice would not be the same. Second, it adds a layer of complexity to the application, which is usually not desired.

The way I see it, this issue can be closed unless current behaviour is not acceptable.

**Comment by joachim-me** [comment]
Enig i konklusjon til @azaxarov . Jeg fjerner buggen fra sprinten.

**Comment by lillelars** [comment]
ikke ansett som bug lenger.. lukker denne.
